### ISSUE TITLE
wsparcie kanału RSS

### ISSUE THREAD

**Issue by neu5** [neu5/zcyklu.pl#10]
@zcyklu czy potrzebujemy utrzymywać wsparcie kanału RSS?
Ktoś tego używa?
W poprzednim frameworku była to funkcjonalność 'z automatu', w aktualnym modelu musiałbym trochę popracować żeby to dodać, dlatego optuję za porzuceniem wsparcia dla kanału RSS.
http://zcyklu.pl/rss.xml

**Comment by zcyklu** [comment]
W garnuszek z tym, porzucamy.

**Comment by neu5** [comment]
Zamykam, stworzyłem wątek: #11
