### ISSUE TITLE
poustawiać kolejność cykli w menu

### ISSUE THREAD

**Issue by neu5** [neu5/zcyklu.pl#13]
należy dodać cykle do odpowiednich kategorii poprzez dodanie referencji w polu **itsCycles** a następnie poustawiać je w odpowiedniej kolejności przy użyciu drag'n'dropa

przykład:
![image](https://user-images.githubusercontent.com/980955/27544234-cdc85242-5a8c-11e7-9d4d-e5ad67dbfcac.png)

**Comment by zcyklu** [comment]
gotowe @neu5

**Comment by neu5** [comment]
sprawdzone i jest ok
