### ISSUE TITLE
dodanie slugów do cykli

### ISSUE THREAD

**Issue by neu5** [neu5/zcyklu.pl#14]
Należy dodać slugi cykli (unikalne URLe),
np. cykl/39/wywiady/
Pamiętaj o **/** na końcu

**Comment by zcyklu** [comment]
Podczas edycji cyklu wyskakuje błąd:
![error](https://user-images.githubusercontent.com/29613880/27549489-6262c856-5a9c-11e7-9186-50d36bf253f1.png)
@neu5 co robić?
Bo to oznacza, że pozycja musi być inaczej oznaczona dla każdej kategorii. Mam więc oznaczać dalej 7, 8, 9... Czy może wprowadzić system 1.1, 1.2, 2.1 itd?

**Comment by neu5** [comment]
@zcyklu slugi powinny być bez domeny:
`http://zcyklu.pl/cykl/15/prime-time/` ->`cykl/15/prime-time/`
Poprawię te co już są dodane :)

W każdym widoku jest taka ikonka konfiguracji (zaznaczona strzałką). 
W widoku cykli możesz sobie tam ustawić, żeby były widoczne np. slugi, dzięki temu od razu widać, które już są dodane i czy są dodane dobrze.
![image](https://user-images.githubusercontent.com/980955/27579000-48dcd784-5b26-11e7-80ee-c293e5e49db5.png)

**Comment by neu5** [comment]
Na szybko wygląda, że jest ok :)
