### ISSUE TITLE
sprawdzenie wpisu 'Kto ich wszystkich otruł'

### ISSUE THREAD

**Issue by neu5** [neu5/zcyklu.pl#20]
http://zcyklu.pl/w-slowach/344/Kto-ich-wszystkich-otrul-Tal-Zbigniewa-Bialasa
To jest niby recenzja a w kategorii `W Słowach`

**Comment by zcyklu** [comment]
@neu5, ktoś źle wrzucił

**Comment by neu5** [comment]
@zcyklu Ok, będziecie to poprawiać?

**Comment by zcyklu** [comment]
Poprawione.

**Comment by neu5** [comment]
@zcyklu To jak poprawione, to przepisz na mnie i daj do kolumny 'zrobione i do sprawdzenia' 👅

**Comment by neu5** [comment]
jest ok 👍
