### ISSUE TITLE
Cykle w pasku po prawej na stronie głównej

### ISSUE THREAD

**Issue by neu5** [neu5/zcyklu.pl#25]
Dodanie pobranych z **contentfula** cykli do paska bocznego na stronie głównej
![image](https://user-images.githubusercontent.com/980955/27594963-955a1ed4-5b5b-11e7-84b5-8c9ec6e04752.png)

**Comment by neu5** [comment]
@zcyklu czy ich kolejność jest istotna?
Aktualna wersja do sprawdzenia na testowym buildzie: https://zcyklu.herokuapp.com/

**Comment by zcyklu** [comment]
@neu5, zamysł był taki, żeby kolejność powtarzała się z menu kategorii, więc aktualna wersja jest super.
