### ISSUE TITLE
Problem z kolorem ramki po najechaniu na cykl w liście cykli na stronie głównej

### ISSUE THREAD

**Issue by neu5** [neu5/zcyklu.pl#26]
Po najechaniu na cykl w pasku bocznym na stronie głównej ramka przechodzi z koloru czarnego i wraca do koloru czarnego.
![](http://g.recordit.co/yJlT1Qe9sE.gif)

Pożądane zachowanie:
Ramka powinna startować ze swojego koloru.

**Comment by zcyklu** [comment]
Tak, poproszę od razu właściwy kolor.

**Comment by neu5** [comment]
@zcyklu Pro Tip: możesz zdjąc labelkę 'question' bo już odpowiedziałaś i wszystko jest jasne!
(tym razem zrobię to ja 😋 )

**Comment by neu5** [comment]
@zcyklu: naprawione, możesz sprawdzać 
🐰

**Comment by zcyklu** [comment]
Piękne <3
