### ISSUE TITLE
info o autorze cyklu gdzieś na stronie cyklu

### ISSUE THREAD

**Issue by neu5** [neu5/zcyklu.pl#39]
@zcyklu masz na to jakiś pomysł?

**Comment by zcyklu** [comment]
Właściwie zastanawiam się teraz, czy na pewno tego potrzebujemy. Jak myślisz? Ewentualnie może być pod opisem cyklu miniatura zdjęcia autora i w tym samym wierszu jego bio.

![o autorze](https://user-images.githubusercontent.com/29613880/30550589-2998b290-9c98-11e7-91ed-4bb0fe3b948f.png)

**Comment by neu5** [comment]
@zcyklu według mnie nie potrzebujemy info o autorze na stronie cyklu. Bardziej bym się zastanawiał, czy nie powinno być tak, że skrót i zdjęcie są klikalne i odnoszą do artykułu, a autor też jest klikalny i odnosi do strony autora. Co o tym sądzisz?
Bo tak to zostajemy w sytuacji, że przejść do strony autora można tylko z podstrony "o nas" albo z artykułu.

**Comment by zcyklu** [comment]
Tak, bardzo dobry pomysł! Tak zróbmy.

**Comment by neu5** [comment]
@zcyklu do sprawdzenia. nie przejmuj się brzydkością, sprawdź tylko czy linki są dobre 😋 
poprawki wizualne będą w innym zadaniu

**Comment by zcyklu** [comment]
Poklikałam trochę i wszystko prowadziło, gdzie miało prowadzić.
