### ISSUE TITLE
na stronie "o nas": odznaczeni autorzy już nieaktywni (wypisani niżej? wyblaknięci?)

### ISSUE THREAD

**Issue by neu5** [neu5/zcyklu.pl#40]
@zcyklu jest ostateczna decyzja jak to ma wyglądać?
nieaktywni autorzy mają być 'wyblaknięci'? mają być klikalni?

**Comment by zcyklu** [comment]
Najbardziej pożądana wersja: najpierw lista z aktywnymi, potem oddzielająca krecha pozioma, potem napis "kiedyś współpracowali z nami" (albo coś podobnego, muszę to skonsultować), a potem klikalni autorzy nieaktywni - na takich samych zasadach, jak aktywni, czyli alfabetycznie i w dwóch kolumnach.

**Comment by neu5** [comment]
@zcyklu: przykładowa wersja do sprawdzenia na
http://zcyklu.herokuapp.com/o-nas

Daj znać jeśli masz uwagi.
Kolejność (chyba) do ustawienia w contentful, możesz to sprawdzić jeśli masz chwilę.

**Comment by zcyklu** [comment]
Wygląda bardzo dobrze (ewentualnie ciut większa przerwa między aktywnymi autorami i napisem "współpracowali z nami"). W contentful zmieniłam już status każdemu autorowi. Kolejność jest alfabetyczna, więc tak jak trzeba :)

**Comment by neu5** [comment]
@zcyklu super!

**Comment by neu5** [comment]
@zcyklu dodałem trochę więcej przestrzeni ;)
