### ISSUE TITLE
wyrzucenie paska z cyklami ze strony głównej dla mniejszych rozdzielczości

### ISSUE THREAD

**Issue by neu5** [neu5/zcyklu.pl#52]

**Comment by neu5** [comment]
@zcyklu do sprawdzenia na
http://zcyklu.herokuapp.com/

**Comment by zcyklu** [comment]
@neu5 wygląda dobrze! Przy okazji zobaczyłam, że menu z kategoriami ni cholery nie mieści się na ekranie telefonu i kiedy się ma się zacząć ładnie opuszczać, to przeskakuje najpierw cała strona do góry i potem dopiero można płynie przescrollować na dół.
