### ISSUE TITLE
Przesunąć niżej tytuł artykułu

### ISSUE THREAD

**Issue by zcyklu** [neu5/zcyklu.pl#53]

**Comment by zcyklu** [comment]
@neu5 ja nie wiem, jakie labels do tego :P

**Comment by neu5** [comment]
@zcyklu do sprawdzenia na
http://zcyklu.herokuapp.com/

**Comment by zcyklu** [comment]
Ahtung, coś się popsuło! Tytuł na stronie artykułu wcale nie jest niżej! A kolorowy pasek z nazwą cyklu się wydłużył!

**Comment by neu5** [comment]
A, zapomniałem o stronie artykułu 😋 
Na razie zrobiłem na stronie głównej. Poprawię i tam niedługo.

**Comment by zcyklu** [comment]
Mój błąd, że nie uściśliłam! A przede wszystkim mi chodzi o stronę artykułu 🙂

**Comment by neu5** [comment]
@zcyklu poprawione, możesz sprawdzać!

**Comment by zcyklu** [comment]
👍
