### ISSUE TITLE
ustalenie jak ma wyglądać nawigacja dla tabletów i mobile

### ISSUE THREAD

**Issue by neu5** [neu5/zcyklu.pl#63]
@zcyklu dla mobile proponuję coś takiego:
https://wireframe.cc/ht8esc

**Comment by zcyklu** [comment]
@neu5 czyli na głównym ekranie na górze będzie logo + kontakt + o nas + ikona menu?
A jak się kliknie menu, to rozwijają się kategorie (typu "na czasie", "w słowach"), a potem klikasz w kategorię i rozwijają się cykle?

**Comment by neu5** [comment]
Tak, tak to widzę właśnie.

**Comment by zcyklu** [comment]
OK, akceptuję :) Jeszcze tylko żeby tam się zmieściły ikonki do FB i Insta (do Insta jeszcze nie mamy na obecnej stronie - a przydałoby się, zamiast RSS).
