### ISSUE TITLE
uaktualnienie ikon do social media w pasku nawigacji

### ISSUE THREAD

**Issue by zcyklu** [neu5/zcyklu.pl#65]
- uaktualnić ikonę FB
- dodać ikonę Instagrama obok FB

@zcyklu proponuję:
https://fontawesome.com/icons/facebook-f?style=brands
https://fontawesome.com/icons/instagram?style=brands

**Comment by neu5** [comment]
@zcyklu do sprawdzenia

**Comment by zcyklu** [comment]
Wszystko ok!
