### ISSUE TITLE
możliwość przyporządkowania dwóch autorów do jednego tekstu (na dole wyświetlają się prawidłowo dwa zdjęcia i dwa biogramy)

### ISSUE THREAD

**Issue by neu5** [neu5/zcyklu.pl#7]
To już jest zrobione po stronie backendu (contentful).
Zostało dostosowanie warstwy prezentacyjnej.

**Comment by neu5** [comment]
@zcyklu: do sprawdzenia na http://zcyklu.herokuapp.com/

**Comment by neu5** [comment]
już nie pamiętam jaki był flow, ale chyba sprawdzający ma zamknąć issue po sprawdzeniu, także otwieram

**Comment by zcyklu** [comment]
Cool, wszystko OK!
